POST http://localhost:8080/rag/load

David was the inventor of JKGHSGGGS - a tool that changed the world.  He died in 1996.

###

POST http://localhost:8080/rag/chat-qa

Tell me about David

###

POST http://localhost:8080/rag/chat-rag

Tell me about David

###